export const FIND_ROOM_SIMPLE_PENDING = 'FIND_ROOM_SIMPLE_PENDING';
export const FIND_ROOM_SIMPLE_SUCCES = 'FIND_ROOM_SIMPLE_SUCCES';
export const FIND_ROOM_SIMPLE_FAILURE = 'FIND_ROOM_SIMPLE_FAILURE';
